import Foundation

nonisolated struct NafsPlan: Identifiable, Sendable {
    let id: String
    let title: String
    let subtitle: String
    let icon: String
    let durationDays: Int
    let steps: [PlanDayStep]
}

nonisolated struct PlanDayStep: Identifiable, Sendable {
    let id: String
    let day: Int
    let reflection: String
    let ayah: String
    let ayahReference: String
    let dhikr: String
    let action: String
}

extension NafsPlan {
    static let all: [NafsPlan] = [
        NafsPlan(
            id: "far_from_allah",
            title: "I feel far from Allah",
            subtitle: "A gentle journey back to His presence",
            icon: "heart.circle.fill",
            durationDays: 14,
            steps: [
                PlanDayStep(id: "f1", day: 1, reflection: "Feeling far from Allah is itself a sign of faith. The hypocrite never notices the distance. Your heart is calling you back.", ayah: "And when My servants ask you concerning Me — indeed I am near.", ayahReference: "Quran 2:186", dhikr: "Say 'La ilaha illallah' 100 times with presence", action: "Pray 2 raka'at and simply talk to Allah about how you feel"),
                PlanDayStep(id: "f2", day: 2, reflection: "The door of tawbah is always open. Allah turns to those who turn to Him. There is no sin too great for His mercy.", ayah: "Say: O My servants who have transgressed against themselves, do not despair of the mercy of Allah.", ayahReference: "Quran 39:53", dhikr: "Say 'Astaghfirullah' 100 times", action: "Write down 3 things you're grateful to Allah for"),
                PlanDayStep(id: "f3", day: 3, reflection: "Start where you are. One sincere prayer is worth more than a hundred empty ones. Quality over quantity.", ayah: "Indeed, the prayer prohibits immorality and wrongdoing.", ayahReference: "Quran 29:45", dhikr: "Say 'SubhanAllah wa bihamdihi' 100 times", action: "Pray at least one salah today with full focus and no phone nearby"),
                PlanDayStep(id: "f4", day: 4, reflection: "The Quran was sent as a healing. Even reading one ayah with understanding can soften a hardened heart.", ayah: "We send down the Quran as a healing and mercy for the believers.", ayahReference: "Quran 17:82", dhikr: "Say 'Alhamdulillah' 100 times", action: "Read Surah Ad-Duhaa (93) slowly with translation and reflect"),
                PlanDayStep(id: "f5", day: 5, reflection: "Your past does not define your future with Allah. Every moment is a new chance to begin again.", ayah: "Allah does not burden a soul beyond that it can bear.", ayahReference: "Quran 2:286", dhikr: "Morning and evening adhkar", action: "Make a specific du'a for guidance and write it where you can see it daily"),
                PlanDayStep(id: "f6", day: 6, reflection: "Consistency beats intensity. A small deed done daily is more beloved to Allah than a large deed done once. Build your foundation brick by brick.", ayah: "The most beloved of deeds to Allah are those that are most consistent, even if they are small.", ayahReference: "Sahih Bukhari", dhikr: "Say 'SubhanAllahi wa bihamdihi, SubhanAllahil Azeem' 100 times", action: "Pick one Sunnah act you can commit to daily — even if it's just smiling at someone"),
                PlanDayStep(id: "f7", day: 7, reflection: "The night prayer is a secret between you and Allah. Even two raka'at in the stillness of the night can transform your heart.", ayah: "And from the night, pray with it as additional worship for you; it is expected that your Lord will raise you to a praised station.", ayahReference: "Quran 17:79", dhikr: "Pray 2 raka'at of Tahajjud and make du'a in sujood", action: "Set an alarm 20 minutes before Fajr and pray in the darkness"),
                PlanDayStep(id: "f8", day: 8, reflection: "Charity purifies the heart. Giving — even a smile or a kind word — connects you to others and to Allah's generosity.", ayah: "Who is it that would loan Allah a goodly loan so He may multiply it for him many times over?", ayahReference: "Quran 2:245", dhikr: "Say 'Allahumma inni as'aluka hubbak' — O Allah, I ask You for Your love", action: "Give sadaqah today, even if it's small. Give it with the intention of drawing near to Allah"),
                PlanDayStep(id: "f9", day: 9, reflection: "Solitude with Allah is medicine. Disconnect from the noise of the world and sit with His words.", ayah: "And We have certainly made the Quran easy for remembrance, so is there any who will remember?", ayahReference: "Quran 54:17", dhikr: "Recite Surah Al-Mulk (67) before sleeping", action: "Spend 15 minutes alone with the Quran — no phone, no distractions"),
                PlanDayStep(id: "f10", day: 10, reflection: "Gratitude opens the door to more blessings. When you thank Allah, He increases you. When you forget, the heart hardens.", ayah: "If you are grateful, I will surely increase you.", ayahReference: "Quran 14:7", dhikr: "Say 'Alhamdulillah' 100 times, reflecting on specific blessings", action: "Write down 10 blessings you normally take for granted"),
                PlanDayStep(id: "f11", day: 11, reflection: "Seek forgiveness not just for sins you remember, but for the ones you've forgotten. Allah's mercy covers what you cannot even see.", ayah: "And seek forgiveness of Allah. Indeed, Allah is Forgiving and Merciful.", ayahReference: "Quran 73:20", dhikr: "Say 'Rabbighfirli' in every sujood today", action: "Make a heartfelt istighfar — speak to Allah as if He's right in front of you"),
                PlanDayStep(id: "f12", day: 12, reflection: "Community strengthens faith. The wolf eats the lone sheep. Find believers who remind you of Allah.", ayah: "And keep yourself patient with those who call upon their Lord in the morning and the evening, seeking His countenance.", ayahReference: "Quran 18:28", dhikr: "Make du'a for someone you know who is also struggling", action: "Reach out to a Muslim friend or community member. Pray together if possible"),
                PlanDayStep(id: "f13", day: 13, reflection: "Reflect on death — not with fear, but with urgency. Life is short. Every prayer could be your last. Let that awaken you.", ayah: "Every soul will taste death. And you will only be given your full compensation on the Day of Resurrection.", ayahReference: "Quran 3:185", dhikr: "Say 'La ilaha illallah wahdahu la sharika lah' 100 times", action: "Visit a cemetery if possible, or reflect on the shortness of life and write your thoughts"),
                PlanDayStep(id: "f14", day: 14, reflection: "You made it. Fourteen days of turning back to Allah. This is not the end — it's the beginning. Keep walking. He is closer than you think.", ayah: "And We are closer to him than his jugular vein.", ayahReference: "Quran 50:16", dhikr: "Complete all morning and evening adhkar with full presence", action: "Write a letter to yourself about this journey. Set your next spiritual goal"),
            ]
        ),
        NafsPlan(
            id: "anger",
            title: "Struggling with anger",
            subtitle: "Quranic tools to cool the fire within",
            icon: "flame.fill",
            durationDays: 7,
            steps: [
                PlanDayStep(id: "a1", day: 1, reflection: "The Prophet ﷺ said the strong person is not the one who wrestles others, but the one who controls themselves when angry. Strength is restraint.", ayah: "Those who spend in prosperity and adversity, who repress anger, and who pardon the people.", ayahReference: "Quran 3:134", dhikr: "Say 'A'udhu billahi min ash-shaytan ir-rajeem' when anger rises", action: "Track every anger episode today. Write: what triggered it, how you reacted"),
                PlanDayStep(id: "a2", day: 2, reflection: "When angry, change your state. If standing, sit. If sitting, lie down. Make wudu — water cools the fire of anger.", ayah: "And if an evil suggestion comes to you from Satan, then seek refuge in Allah.", ayahReference: "Quran 7:200", dhikr: "Say 'La hawla wa la quwwata illa billah' 33 times", action: "Practice the 4-4-4 breathing technique three times today"),
                PlanDayStep(id: "a3", day: 3, reflection: "Anger often hides fear, hurt, or unmet needs. Look beneath the surface. What are you really feeling?", ayah: "Repel evil with that which is better, and thereupon the one with enmity will become a devoted friend.", ayahReference: "Quran 41:34", dhikr: "Say 'SubhanAllah' 100 times slowly", action: "Before reacting to frustration today, pause for 10 seconds and make du'a silently"),
                PlanDayStep(id: "a4", day: 4, reflection: "Silence is a powerful tool. The Prophet ﷺ said: 'Whoever believes in Allah and the Last Day, let him speak good or remain silent.' Silence protects you from regret.", ayah: "Not a word does he utter but there is a watcher by him ready to record it.", ayahReference: "Quran 50:18", dhikr: "Say 'Allahumma inni a'udhu bika min sharri sam'i wa min sharri basari wa min sharri lisani wa min sharri qalbi' — seeking refuge from the evil of tongue and heart", action: "Practice 5 minutes of complete silence when you feel anger rising. Walk away if needed"),
                PlanDayStep(id: "a5", day: 5, reflection: "Forgiveness is not weakness — it is strength. Holding onto anger poisons your own heart more than anyone else's.", ayah: "And let them pardon and overlook. Would you not like that Allah should forgive you?", ayahReference: "Quran 24:22", dhikr: "Make du'a for someone who has wronged you", action: "Write a forgiveness letter — you don't have to send it, but release the weight from your heart"),
                PlanDayStep(id: "a6", day: 6, reflection: "Physical health affects emotional health. Exercise releases tension that builds into anger. Move your body as an act of worship.", ayah: "And He found you lost and guided you.", ayahReference: "Quran 93:7", dhikr: "Say 'La hawla wa la quwwata illa billah' throughout the day", action: "Exercise for 20 minutes today — walk, run, or stretch. Dedicate it as worship"),
                PlanDayStep(id: "a7", day: 7, reflection: "You've spent a week working on your anger. The nafs is tamed through practice and return. Reset. Rebuild. Keep going.", ayah: "And those who strive for Us — We will surely guide them to Our ways.", ayahReference: "Quran 29:69", dhikr: "Complete full morning and evening adhkar", action: "Reflect on the week. Write what triggered you, how you responded differently, and your growth"),
            ]
        ),
        NafsPlan(
            id: "grief",
            title: "Going through grief",
            subtitle: "Let Allah carry what you cannot",
            icon: "leaf.fill",
            durationDays: 14,
            steps: [
                PlanDayStep(id: "g1", day: 1, reflection: "Grief is not weakness. The Prophet ﷺ wept when his son Ibrahim passed. Tears are mercy from Allah, not a sign of weak faith.", ayah: "Indeed, to Allah we belong and to Him we shall return.", ayahReference: "Quran 2:156", dhikr: "Recite 'Inna lillahi wa inna ilayhi raji'un' with reflection", action: "Allow yourself to feel whatever you're feeling today without judgment. Write one sentence about your loss"),
                PlanDayStep(id: "g2", day: 2, reflection: "Allah tests those He loves. Patience in hardship is one of the highest forms of worship.", ayah: "And We will surely test you with something of fear and hunger and a loss of wealth and lives and fruits, but give good tidings to the patient.", ayahReference: "Quran 2:155", dhikr: "Say 'HasbunAllahu wa ni'mal wakeel' 100 times", action: "Speak to someone you trust about how you feel. Connection is healing"),
                PlanDayStep(id: "g3", day: 3, reflection: "The akhirah is where all wrongs are righted and all losses restored. This life is temporary, but your patience is eternal reward.", ayah: "Indeed, the patient will be given their reward without account.", ayahReference: "Quran 39:10", dhikr: "Make du'a for the deceased or for your healing", action: "Read Surah Ash-Sharh (94) — The Relief — and sit with its message"),
                PlanDayStep(id: "g4", day: 4, reflection: "It's okay to not be okay. Grief comes in waves — some days are better, some harder. Don't judge your healing by a timeline.", ayah: "He said, I only complain of my suffering and my grief to Allah.", ayahReference: "Quran 12:86", dhikr: "Say 'Allahumma ajirni fi musibati wakhlufli khairan minha' — O Allah, reward me in my affliction and replace it with something better", action: "Do something kind for yourself today — rest, eat well, take a walk in nature"),
                PlanDayStep(id: "g5", day: 5, reflection: "The Prophet ﷺ lost his beloved wife Khadijah, his uncle, his children. He grieved deeply and still served Allah. Grief and faith coexist.", ayah: "Verily, with hardship comes ease.", ayahReference: "Quran 94:6", dhikr: "Recite Surah Ad-Duhaa (93) and reflect on Allah's care for you", action: "Share a beautiful memory of what you've lost with someone you trust"),
                PlanDayStep(id: "g6", day: 6, reflection: "Helping others who are hurting can heal your own heart. Service is a form of sabr — it redirects pain into purpose.", ayah: "And whoever does righteousness — it is for his own soul.", ayahReference: "Quran 45:15", dhikr: "Say 'Alhamdulillah ala kulli haal' — All praise to Allah in every condition", action: "Do an act of kindness for someone else who is going through difficulty"),
                PlanDayStep(id: "g7", day: 7, reflection: "Du'a is the weapon of the believer. Pour your heart out to Allah — He hears every silent cry and every whispered plea.", ayah: "And your Lord says: Call upon Me, I will respond to you.", ayahReference: "Quran 40:60", dhikr: "Make a long, personal du'a in sujood — speak freely to Allah", action: "Write a du'a from your heart and read it after every salah today"),
                PlanDayStep(id: "g8", day: 8, reflection: "Nature heals. The sky, the trees, the rain — all are signs of Allah's mercy and continuity. Life goes on, and so will you.", ayah: "And the earth — We spread it out and cast therein firmly set mountains and made grow therein something of every beautiful kind.", ayahReference: "Quran 50:7", dhikr: "Walk outside and say 'SubhanAllah' at every beautiful thing you notice", action: "Spend 20 minutes outdoors. Observe creation and let it soothe your heart"),
                PlanDayStep(id: "g9", day: 9, reflection: "Sleep can be worship. Rest when you need it. Allah designed the night as a covering — there is no shame in retreating to heal.", ayah: "And We made your sleep a means of rest.", ayahReference: "Quran 78:9", dhikr: "Recite the 3 Quls and Ayatul Kursi before sleep", action: "Go to bed early tonight. Make du'a before sleeping and let your heart rest"),
                PlanDayStep(id: "g10", day: 10, reflection: "Remembering the good times is not a setback — it's gratitude. Thank Allah for what was, even as you mourn what is gone.", ayah: "And He gave you from all you asked of Him. And if you should count the favor of Allah, you could not enumerate them.", ayahReference: "Quran 14:34", dhikr: "Say 'Alhamdulillah' 100 times with specific memories in mind", action: "Write down 5 beautiful moments you are grateful for, connected to your loss"),
                PlanDayStep(id: "g11", day: 11, reflection: "Anger is a stage of grief. If you feel angry at the situation, at the world, even at yourself — acknowledge it. Then hand it to Allah.", ayah: "And those who, when struck by misfortune, say: Indeed we belong to Allah, and indeed to Him we will return.", ayahReference: "Quran 2:156", dhikr: "Say 'La ilaha illallah' when anger or frustration surfaces", action: "Journal about any anger you've been holding. Release it on paper, then make du'a"),
                PlanDayStep(id: "g12", day: 12, reflection: "Sadaqah jariyah — ongoing charity — is a way to honor those who have passed. Their reward continues through your good deeds.", ayah: "Whatever you spend of good — it is for yourselves.", ayahReference: "Quran 2:272", dhikr: "Make du'a for those who have passed after every salah", action: "Give sadaqah in honor of your loved one or your healing"),
                PlanDayStep(id: "g13", day: 13, reflection: "Healing is not linear. You may feel better one day and worse the next. This is normal. Trust the process and trust Allah's timing.", ayah: "Perhaps you hate a thing and it is good for you; and perhaps you love a thing and it is bad for you. And Allah knows, while you know not.", ayahReference: "Quran 2:216", dhikr: "Say 'Tawakkaltu alAllah' — I place my trust in Allah — throughout the day", action: "Be patient with yourself today. If it's a hard day, just do your adhkar and rest"),
                PlanDayStep(id: "g14", day: 14, reflection: "Two weeks of walking through grief with Allah by your side. You are braver than you know. The journey continues — but you are not alone.", ayah: "Allah is the ally of those who believe. He brings them out from darknesses into the light.", ayahReference: "Quran 2:257", dhikr: "Complete all adhkar and make a long, grateful du'a", action: "Write a letter to your future self about what you've learned. Set one intention for moving forward"),
            ]
        ),
        NafsPlan(
            id: "bad_habit",
            title: "Quit a bad habit",
            subtitle: "Discipline the nafs, one day at a time",
            icon: "arrow.uturn.backward.circle.fill",
            durationDays: 21,
            steps: [
                PlanDayStep(id: "b1", day: 1, reflection: "Every person sins. The best of sinners are those who repent. You are not defined by your lowest moments.", ayah: "And turn to Allah in repentance, all of you, O believers, that you might succeed.", ayahReference: "Quran 24:31", dhikr: "Say 'Astaghfirullah wa atubu ilayh' 100 times", action: "Write down the habit, its triggers, and what you want to replace it with"),
                PlanDayStep(id: "b2", day: 2, reflection: "Replace, don't just remove. The nafs needs to be redirected, not starved. Fill the void with something better.", ayah: "Indeed, good deeds do away with misdeeds.", ayahReference: "Quran 11:114", dhikr: "Say 'SubhanAllahi wa bihamdihi, SubhanAllahil Azeem' 100 times", action: "When the urge comes today, immediately do 2 raka'at and make du'a"),
                PlanDayStep(id: "b3", day: 3, reflection: "Environment shapes behavior. The Prophet ﷺ taught us that a person is on the religion of their close friends. Guard your inputs.", ayah: "O you who have believed, fear Allah and be with those who are truthful.", ayahReference: "Quran 9:119", dhikr: "Morning and evening adhkar completely", action: "Remove one trigger from your environment. Delete an app, move something, change a routine"),
                PlanDayStep(id: "b4", day: 4, reflection: "The nafs has three levels: the commanding nafs, the self-reproaching nafs, and the tranquil nafs. Every time you resist, you rise.", ayah: "And I do swear by the self-reproaching soul.", ayahReference: "Quran 75:2", dhikr: "Say 'Ya Muqallib al-quloob, thabbit qalbi ala deenik' — O Turner of hearts, keep my heart firm on Your religion", action: "When the urge comes, delay acting on it by 10 minutes. Use that time for dhikr"),
                PlanDayStep(id: "b5", day: 5, reflection: "Accountability accelerates change. Find someone trustworthy who can check on your progress without judgment.", ayah: "And cooperate in righteousness and piety, but do not cooperate in sin and aggression.", ayahReference: "Quran 5:2", dhikr: "Say 'Astaghfirullah' 100 times with sincerity", action: "Tell one trusted person about your goal. Ask them to check in on you weekly"),
                PlanDayStep(id: "b6", day: 6, reflection: "Fasting trains the nafs like nothing else. When you deny the body what it craves in obedience to Allah, willpower grows.", ayah: "O you who have believed, fasting is prescribed for you as it was prescribed for those before you that you may become righteous.", ayahReference: "Quran 2:183", dhikr: "Say 'SubhanAllah wa bihamdihi' 100 times", action: "Fast today (if able) to strengthen your willpower and self-control"),
                PlanDayStep(id: "b7", day: 7, reflection: "One week in. If you've slipped, don't despair. The shaytan wants you to give up. Every restart is an act of courage.", ayah: "And whoever does a wrong or wrongs himself but then seeks forgiveness of Allah will find Allah Forgiving and Merciful.", ayahReference: "Quran 4:110", dhikr: "Pray 2 raka'at of tawbah and ask Allah for strength", action: "Review the week. Celebrate wins, learn from slips. Adjust your strategy"),
                PlanDayStep(id: "b8", day: 8, reflection: "Fill your time with purpose. Idle hands and an idle mind are the shaytan's playground. Stay busy with good.", ayah: "So when you have finished your duties, then stand up for worship.", ayahReference: "Quran 94:7", dhikr: "Recite Surah Al-Asr (103) and reflect on the value of time", action: "Create a daily schedule that fills vulnerable times with productive activities"),
                PlanDayStep(id: "b9", day: 9, reflection: "Physical health supports spiritual health. Exercise, eat well, sleep enough. A tired body weakens resolve.", ayah: "Eat and drink, but be not excessive. Indeed, He likes not those who commit excess.", ayahReference: "Quran 7:31", dhikr: "Say 'Alhamdulillah' before and after meals with awareness", action: "Exercise for 20 minutes and drink plenty of water today"),
                PlanDayStep(id: "b10", day: 10, reflection: "Knowledge protects. Learn about the spiritual consequences of your habit and the rewards of leaving it for Allah's sake.", ayah: "Are those who know equal to those who do not know?", ayahReference: "Quran 39:9", dhikr: "Listen to a lecture about tawbah and self-improvement", action: "Read or listen to content about the Islamic perspective on your specific struggle"),
                PlanDayStep(id: "b11", day: 11, reflection: "Du'a is your most powerful tool. Allah can change your heart in an instant. Never underestimate the power of sincerely asking Him.", ayah: "And your Lord says: Call upon Me, I will respond to you.", ayahReference: "Quran 40:60", dhikr: "Make du'a in the last third of the night", action: "Write a specific du'a asking Allah to remove this habit from your life"),
                PlanDayStep(id: "b12", day: 12, reflection: "The companions struggled too. They were human. What made them great was their refusal to give up on themselves or on Allah.", ayah: "And those who strive for Us — We will surely guide them to Our ways.", ayahReference: "Quran 29:69", dhikr: "Say 'Allahu Akbar' 100 times — Allah is Greater than any temptation", action: "Read about a companion who overcame difficulty and draw strength from their story"),
                PlanDayStep(id: "b13", day: 13, reflection: "Visualize who you want to be on the Day of Judgment. That version of you made the hard choices today.", ayah: "O you who have believed, fear Allah. And let every soul look to what it has put forth for tomorrow.", ayahReference: "Quran 59:18", dhikr: "Pray all 5 salah on time today", action: "Write a letter from your future self thanking you for the changes you're making now"),
                PlanDayStep(id: "b14", day: 14, reflection: "Two weeks. Your neural pathways are rewiring. The urges may still come, but you are building new patterns. Keep going.", ayah: "Indeed, Allah will not change the condition of a people until they change what is in themselves.", ayahReference: "Quran 13:11", dhikr: "Say 'La ilaha illallah wahdahu la sharika lah' 100 times", action: "Reward yourself with something halal that you enjoy. Celebrate the progress"),
                PlanDayStep(id: "b15", day: 15, reflection: "Shaytan will try to convince you that you've done enough and can 'just this once' return. Recognize this trap.", ayah: "Indeed, Satan is an enemy to you; so take him as an enemy.", ayahReference: "Quran 35:6", dhikr: "Say 'A'udhu billahi min ash-shaytan ir-rajeem' whenever tempted", action: "Identify your top 3 rationalizations and write counter-arguments for each"),
                PlanDayStep(id: "b16", day: 16, reflection: "Gratitude keeps you grounded. When you see how far you've come, you won't want to go back.", ayah: "If you are grateful, I will surely increase you.", ayahReference: "Quran 14:7", dhikr: "Say 'Alhamdulillah' 100 times", action: "List 5 positive changes you've noticed since starting this plan"),
                PlanDayStep(id: "b17", day: 17, reflection: "Serve others. When you help someone else, your own struggles feel lighter. Purpose is the antidote to emptiness.", ayah: "And whoever saves one — it is as if he had saved mankind entirely.", ayahReference: "Quran 5:32", dhikr: "Make du'a for others who are struggling with the same habit", action: "Do a meaningful act of service today — volunteer, help a neighbor, feed someone"),
                PlanDayStep(id: "b18", day: 18, reflection: "The Quran is a healing. Read it not as a task but as medicine. Let the words enter your heart.", ayah: "O mankind, there has come to you instruction from your Lord and healing for what is in the breasts.", ayahReference: "Quran 10:57", dhikr: "Read one page of Quran with deep reflection", action: "Find an ayah that speaks to your struggle and memorize it as your anchor"),
                PlanDayStep(id: "b19", day: 19, reflection: "Sleep hygiene matters. Many bad habits are worst at night when you're tired and alone. Protect your nights.", ayah: "And We made the night as a covering.", ayahReference: "Quran 78:10", dhikr: "Recite the sleep adhkar fully tonight", action: "Put your phone in another room before bed. Read Quran or a book instead"),
                PlanDayStep(id: "b20", day: 20, reflection: "Almost there. You are proving to yourself that change is possible. Allah sees every struggle, every resistance, every tear.", ayah: "Indeed, Allah does not allow to be lost the reward of those who do good.", ayahReference: "Quran 9:120", dhikr: "Pray 2 extra raka'at of shukr (gratitude)", action: "Call or message your accountability partner and share your progress"),
                PlanDayStep(id: "b21", day: 21, reflection: "Twenty-one days. They say it takes this long to form a new habit. But your journey doesn't end here — it transforms here. You've built a foundation. Now maintain it with tawakkul and tawbah.", ayah: "And whoever fears Allah — He will make for him a way out. And will provide for him from where he does not expect.", ayahReference: "Quran 65:2-3", dhikr: "Complete all adhkar and make a comprehensive du'a of gratitude", action: "Write your personal plan for maintaining this change. Include triggers, responses, and your support system"),
            ]
        ),
        NafsPlan(
            id: "ramadan_prep",
            title: "Ramadan preparation",
            subtitle: "Arrive at Ramadan with a ready heart",
            icon: "moon.stars.fill",
            durationDays: 30,
            steps: [
                PlanDayStep(id: "r1", day: 1, reflection: "Ramadan is a guest that comes once a year. Prepare your heart before it arrives so you can receive its full blessing.", ayah: "The month of Ramadan in which was revealed the Quran, a guidance for mankind.", ayahReference: "Quran 2:185", dhikr: "Say 'Allahumma ballighna Ramadan' — O Allah, let us reach Ramadan", action: "Set your Ramadan goals: spiritual, physical, social. Write them down"),
                PlanDayStep(id: "r2", day: 2, reflection: "Begin adjusting your sleep schedule now. Wake earlier, sleep earlier. The barakah of the early morning is real.", ayah: "And in the hours before dawn they would ask forgiveness.", ayahReference: "Quran 51:18", dhikr: "Pray Tahajjud — even 2 raka'at before Fajr", action: "Set an alarm 30 minutes before Fajr and use the time for istighfar"),
                PlanDayStep(id: "r3", day: 3, reflection: "Practice fasting before Ramadan. Monday and Thursday fasts are Sunnah and train your body and nafs.", ayah: "O you who have believed, decreed upon you is fasting as it was decreed upon those before you that you may become righteous.", ayahReference: "Quran 2:183", dhikr: "Say 'SubhanAllah' 33, 'Alhamdulillah' 33, 'Allahu Akbar' 34 after every salah", action: "Fast today (Monday or Thursday) to prepare your body"),
                PlanDayStep(id: "r4", day: 4, reflection: "The Quran was revealed in Ramadan. Begin building your relationship with it now so you can dive deep when the month arrives.", ayah: "Indeed, We sent it down during the Night of Decree.", ayahReference: "Quran 97:1", dhikr: "Read 2 pages of Quran with translation after Fajr", action: "Choose a Quran reading goal for Ramadan — a full khatm or specific surahs — and write it down"),
                PlanDayStep(id: "r5", day: 5, reflection: "Charity in Ramadan is multiplied. Start planning your sadaqah and zakat now so you can give generously.", ayah: "The example of those who spend their wealth in the way of Allah is like a seed which grows seven ears.", ayahReference: "Quran 2:261", dhikr: "Say 'Allahumma barik lana fi Rajab wa Sha'ban wa ballighna Ramadan'", action: "Research charities and set a Ramadan giving budget"),
                PlanDayStep(id: "r6", day: 6, reflection: "Reduce screen time now. The hours you spend scrolling could be hours of worship in Ramadan. Train yourself.", ayah: "By time, indeed mankind is in loss.", ayahReference: "Quran 103:1-2", dhikr: "Replace 30 minutes of phone time with dhikr", action: "Set daily screen time limits on your most-used apps"),
                PlanDayStep(id: "r7", day: 7, reflection: "Strengthen your salah before Ramadan. If you're struggling with the 5 daily prayers, focus on consistency now.", ayah: "Indeed, prayer has been decreed upon the believers a decree of specified times.", ayahReference: "Quran 4:103", dhikr: "Pray all 5 salah on time with the opening du'a", action: "Add at least 2 raka'at of Sunnah before or after each obligatory prayer"),
                PlanDayStep(id: "r8", day: 8, reflection: "Forgive before Ramadan. Enter the blessed month with a clean heart. Grudges weigh down the soul.", ayah: "And let them pardon and overlook. Would you not like that Allah should forgive you?", ayahReference: "Quran 24:22", dhikr: "Make du'a for those who have wronged you", action: "Reach out to anyone you need to reconcile with. Clear your heart"),
                PlanDayStep(id: "r9", day: 9, reflection: "Learn the fiqh of fasting — what breaks it, what doesn't, the Sunnah acts. Knowledge makes worship more meaningful.", ayah: "Say: Are those who know equal to those who do not know?", ayahReference: "Quran 39:9", dhikr: "Read a chapter about Ramadan fiqh", action: "Study the rulings of fasting from a reliable source"),
                PlanDayStep(id: "r10", day: 10, reflection: "Prepare your du'a list. Ramadan is a time when du'as are answered. Know what you want to ask for.", ayah: "And when My servants ask you concerning Me — indeed I am near. I respond to the invocation of every supplicant when he calls upon Me.", ayahReference: "Quran 2:186", dhikr: "Write your du'a list — personal, family, ummah", action: "Memorize at least 3 comprehensive du'as from the Sunnah"),
                PlanDayStep(id: "r11", day: 11, reflection: "Reduce your food intake gradually. Ramadan is not about feasting at iftar — it's about spiritual nourishment.", ayah: "Eat and drink, but be not excessive.", ayahReference: "Quran 7:31", dhikr: "Say 'Bismillah' before eating and 'Alhamdulillah' after", action: "Eat lighter meals today. Plan simple, healthy iftar menus for Ramadan"),
                PlanDayStep(id: "r12", day: 12, reflection: "I'tikaf is a powerful Sunnah — dedicating time in the masjid to worship. Plan for at least a partial i'tikaf in the last 10 nights.", ayah: "And We charged Abraham and Ishmael: Purify My House for those who perform tawaf and those who are staying there for worship.", ayahReference: "Quran 2:125", dhikr: "Pray Duha (forenoon) prayer — 2 or 4 raka'at", action: "Research i'tikaf at your local masjid and plan your schedule"),
                PlanDayStep(id: "r13", day: 13, reflection: "Taraweeh prayers are the heartbeat of Ramadan nights. If you're not used to long prayers, start building stamina.", ayah: "They used to sleep but little of the night.", ayahReference: "Quran 51:17", dhikr: "Pray Witr with long du'a al-Qunut", action: "Pray 8 raka'at of night prayer tonight to build endurance"),
                PlanDayStep(id: "r14", day: 14, reflection: "The tongue can earn or destroy. Practice guarding your speech — no backbiting, lying, or harsh words.", ayah: "O you who have believed, let not a people ridicule another people.", ayahReference: "Quran 49:11", dhikr: "Say 'Allahumma inni a'udhu bika min sharri lisani' — O Allah, I seek refuge from the evil of my tongue", action: "Go one full day without complaining, backbiting, or speaking negatively"),
                PlanDayStep(id: "r15", day: 15, reflection: "Halfway there. You're building habits that will make Ramadan transformative. Keep the momentum.", ayah: "And whoever obeys Allah and His Messenger has certainly attained a great attainment.", ayahReference: "Quran 33:71", dhikr: "Say 'SubhanAllahi wa bihamdihi, SubhanAllahil Azeem' 100 times", action: "Review your Ramadan goals. Adjust and refine them"),
                PlanDayStep(id: "r16", day: 16, reflection: "Community matters in Ramadan. Plan to break fast with others and pray taraweeh in congregation.", ayah: "And hold firmly to the rope of Allah all together and do not become divided.", ayahReference: "Quran 3:103", dhikr: "Make du'a for the Muslim ummah", action: "Invite someone to share iftar during Ramadan. Build your Ramadan community"),
                PlanDayStep(id: "r17", day: 17, reflection: "Memorize new Quran to recite in your prayers. Even one new surah makes your salah richer.", ayah: "And We have certainly made the Quran easy for remembrance.", ayahReference: "Quran 54:17", dhikr: "Memorize 3 new ayat today", action: "Start memorizing a new surah to complete before Ramadan begins"),
                PlanDayStep(id: "r18", day: 18, reflection: "Gratitude unlocks barakah. As Ramadan approaches, be thankful that Allah has given you another chance to witness it.", ayah: "If you are grateful, I will surely increase you.", ayahReference: "Quran 14:7", dhikr: "Say 'Alhamdulillah' 100 times", action: "Write a letter of gratitude to Allah for another Ramadan"),
                PlanDayStep(id: "r19", day: 19, reflection: "Lower your gaze — from haram content, from comparing yourself to others, from distractions that pull your heart away.", ayah: "Tell the believing men to reduce some of their vision and guard their private parts.", ayahReference: "Quran 24:30", dhikr: "Say 'Astaghfirullah' every time you catch yourself looking at something you shouldn't", action: "Do a digital detox: unfollow accounts that don't benefit your akhirah"),
                PlanDayStep(id: "r20", day: 20, reflection: "Laylatul Qadr is better than a thousand months. Prepare to seek it in the last 10 nights with worship and du'a.", ayah: "The Night of Decree is better than a thousand months.", ayahReference: "Quran 97:3", dhikr: "Memorize the du'a: 'Allahumma innaka afuwwun tuhibbul afwa fa'fu anni'", action: "Plan your last 10 nights schedule — which prayers, which du'as, how to maximize each night"),
                PlanDayStep(id: "r21", day: 21, reflection: "Tawbah before Ramadan. Enter the month with sincere repentance and a clean slate.", ayah: "And turn to Allah in repentance, all of you, O believers, that you might succeed.", ayahReference: "Quran 24:31", dhikr: "Pray 2 raka'at of tawbah", action: "Make a comprehensive istighfar — ask forgiveness for every sin you can remember"),
                PlanDayStep(id: "r22", day: 22, reflection: "Prepare your home for Ramadan. Clean your space, set up a prayer corner, stock healthy suhoor foods.", ayah: "And purify My House for those who walk around it.", ayahReference: "Quran 22:26", dhikr: "Say 'Bismillah' as you clean and prepare", action: "Set up a dedicated worship space and shop for healthy suhoor essentials"),
                PlanDayStep(id: "r23", day: 23, reflection: "Connection to the masjid strengthens faith. The Prophet ﷺ said the masjid is the garden of Paradise.", ayah: "The mosques of Allah are only to be maintained by those who believe in Allah and the Last Day.", ayahReference: "Quran 9:18", dhikr: "Pray at least one salah in the masjid today", action: "Visit your local masjid and learn about their Ramadan programs"),
                PlanDayStep(id: "r24", day: 24, reflection: "Patience is the theme of Ramadan. Sabr in hunger, sabr in worship, sabr with people. Start practicing now.", ayah: "O you who have believed, seek help through patience and prayer.", ayahReference: "Quran 2:153", dhikr: "Say 'Ya Saboor' (O Most Patient) 100 times", action: "Practice patience in one difficult situation today without complaining"),
                PlanDayStep(id: "r25", day: 25, reflection: "Teach someone what you've learned. Sharing knowledge multiplies its reward and deepens your understanding.", ayah: "Invite to the way of your Lord with wisdom and good instruction.", ayahReference: "Quran 16:125", dhikr: "Share one beneficial reminder with a friend or family member", action: "Help someone else prepare for Ramadan — share tips, resources, or encouragement"),
                PlanDayStep(id: "r26", day: 26, reflection: "Review your relationship with music, entertainment, and social media. Ramadan is a time to detox from distractions.", ayah: "Has the time not come for those who have believed that their hearts should become humbly submissive at the remembrance of Allah?", ayahReference: "Quran 57:16", dhikr: "Replace entertainment time with Quran listening", action: "Create a Ramadan media plan — what you'll consume and what you'll avoid"),
                PlanDayStep(id: "r27", day: 27, reflection: "Intention is everything. Renew your niyyah for Ramadan. Why are you fasting? What do you hope to gain?", ayah: "And they were not commanded except to worship Allah, being sincere to Him in religion.", ayahReference: "Quran 98:5", dhikr: "Say 'Allahumma inni nawaytu siyama ghadin min shahri Ramadan' — practice your niyyah", action: "Write your sincere intentions for Ramadan. What do you want to change?"),
                PlanDayStep(id: "r28", day: 28, reflection: "The Prophet ﷺ was the most generous in Ramadan, like a wind bringing rain. Plan how you will give.", ayah: "You will never attain righteousness until you spend from that which you love.", ayahReference: "Quran 3:92", dhikr: "Calculate your zakat if applicable", action: "Finalize your Ramadan charity plan — daily sadaqah, zakat, feeding the fasting"),
                PlanDayStep(id: "r29", day: 29, reflection: "Almost Ramadan. Your heart has been preparing for 29 days. You are ready. Trust in Allah and enter with hope.", ayah: "So verily, with the hardship, there is relief.", ayahReference: "Quran 94:5", dhikr: "Make du'a that Allah accepts your Ramadan", action: "Fast today as a final preparation. Make your last pre-Ramadan du'a"),
                PlanDayStep(id: "r30", day: 30, reflection: "Ramadan is here — or nearly here. You have prepared your heart, body, and soul. Enter this blessed month with gratitude, humility, and hope. May Allah accept from you.", ayah: "The month of Ramadan in which was revealed the Quran, a guidance for the people and clear proofs of guidance and criterion.", ayahReference: "Quran 2:185", dhikr: "Complete all adhkar and make a comprehensive du'a", action: "Welcome Ramadan with a clean heart. Say 'Allahu Akbar' and begin your journey"),
            ]
        ),
        NafsPlan(
            id: "salah_consistency",
            title: "Consistency in Salah",
            subtitle: "Make prayer the anchor of your day",
            icon: "checkmark.seal.fill",
            durationDays: 10,
            steps: [
                PlanDayStep(id: "s1", day: 1, reflection: "Salah is the first thing you will be asked about on the Day of Judgment. It is not a burden — it is a lifeline.", ayah: "Indeed, prayer has been decreed upon the believers a decree of specified times.", ayahReference: "Quran 4:103", dhikr: "Say 'Allahumma a'inni ala dhikrika wa shukrika wa husni ibadatik' after every salah", action: "Pray all 5 salah today. Set alarms for each one. No excuses, even if late"),
                PlanDayStep(id: "s2", day: 2, reflection: "Start with the easiest prayer to pray on time and build from there. Small wins create momentum.", ayah: "Guard strictly the prayers, especially the middle prayer, and stand before Allah in devout obedience.", ayahReference: "Quran 2:238", dhikr: "Say 'SubhanAllah' 33 times after each salah", action: "Identify your strongest and weakest prayer. Focus extra attention on the weakest one today"),
                PlanDayStep(id: "s3", day: 3, reflection: "Pray where you can see the sky. The change of environment alone can transform your khushu'.", ayah: "Successful indeed are the believers who are humble in their prayers.", ayahReference: "Quran 23:1-2", dhikr: "Make dhikr between the adhan and iqamah — du'a is not rejected at this time", action: "Find a quiet, clean space for at least one prayer today. Put your phone in another room"),
                PlanDayStep(id: "s4", day: 4, reflection: "Understand what you recite. When you know what Al-Fatiha means, every raka'ah becomes a conversation with Allah.", ayah: "So recite what is easy from the Quran.", ayahReference: "Quran 73:20", dhikr: "Memorize the meaning of Al-Fatiha and recite with understanding", action: "Read the tafsir of Al-Fatiha and pray your next salah reflecting on its meaning"),
                PlanDayStep(id: "s5", day: 5, reflection: "The Sunnah prayers are a shield for the obligatory ones. They fill the gaps and earn extra reward.", ayah: "And from the night, prostrate to Him and exalt Him a long part of the night.", ayahReference: "Quran 76:26", dhikr: "Pray 2 raka'at Sunnah before Fajr and 2 after Dhuhr", action: "Add at least one set of Sunnah raka'at to your daily routine"),
                PlanDayStep(id: "s6", day: 6, reflection: "Sujood is when you are closest to Allah. Make long sujood and pour your heart out in du'a.", ayah: "Prostrate and draw near to Allah.", ayahReference: "Quran 96:19", dhikr: "Stay in sujood for an extra 30 seconds in each prayer, making du'a", action: "In one salah today, make your sujood significantly longer with heartfelt du'a"),
                PlanDayStep(id: "s7", day: 7, reflection: "Praying in congregation multiplies the reward by 27 times. Community strengthens commitment.", ayah: "And bow with those who bow in worship and obedience.", ayahReference: "Quran 2:43", dhikr: "Attend one congregational prayer today if possible", action: "Pray at least one salah in congregation — at the masjid or with family"),
                PlanDayStep(id: "s8", day: 8, reflection: "Wudu is not just physical cleansing — it is spiritual preparation. Make wudu slowly with mindfulness.", ayah: "O you who have believed, when you rise to perform prayer, wash your faces and your forearms.", ayahReference: "Quran 5:6", dhikr: "Say 'Bismillah' before wudu and the shahadah after", action: "Make wudu today as an act of worship itself — slowly, mindfully, with du'a"),
                PlanDayStep(id: "s9", day: 9, reflection: "If you miss a prayer, don't let shame keep you from the next one. Shaytan wants one miss to become a streak.", ayah: "And establish prayer for My remembrance.", ayahReference: "Quran 20:14", dhikr: "Say 'Astaghfirullah' if you miss a prayer, then make it up immediately", action: "If you've missed prayers in the past, begin making them up — even one per day"),
                PlanDayStep(id: "s10", day: 10, reflection: "Ten days of building salah consistency. You are rewriting your habits. The prayer will become the coolness of your eyes, just as it was for the Prophet ﷺ.", ayah: "Indeed, I am Allah. There is no deity except Me, so worship Me and establish prayer for My remembrance.", ayahReference: "Quran 20:14", dhikr: "Complete all prayers on time with full adhkar after each", action: "Reflect on your 10-day journey. Write about how your relationship with salah has changed"),
            ]
        ),
        NafsPlan(
            id: "anxiety",
            title: "Anxiety and overthinking",
            subtitle: "Find stillness through dhikr and tawakkul",
            icon: "brain.head.profile",
            durationDays: 7,
            steps: [
                PlanDayStep(id: "x1", day: 1, reflection: "Anxiety is the mind living in the future. Islam teaches us to trust Allah's plan while doing our part. Control what you can, surrender the rest.", ayah: "Unquestionably, by the remembrance of Allah hearts are assured.", ayahReference: "Quran 13:28", dhikr: "Say 'HasbunAllahu wa ni'mal wakeel' 100 times — Allah is sufficient for us", action: "Do the 4-4-4 breathing exercise 3 times today while saying 'Allah' on each exhale"),
                PlanDayStep(id: "x2", day: 2, reflection: "The Prophet ﷺ taught us: 'If the whole world gathered to harm you, they could not harm you except what Allah has decreed.' This is freedom.", ayah: "And whoever puts their trust in Allah, then He will suffice him.", ayahReference: "Quran 65:3", dhikr: "Recite Ayatul Kursi after every salah", action: "Write down every worry. Next to each one write: 'Can I control this?' If no — surrender it to Allah"),
                PlanDayStep(id: "x3", day: 3, reflection: "Overthinking is often the nafs trapped in circular fear. Break the loop with physical movement and dhikr — both ground you in the present.", ayah: "Do not grieve; indeed Allah is with us.", ayahReference: "Quran 9:40", dhikr: "Walk for 15 minutes while saying 'SubhanAllah' with each step", action: "Limit news and social media to 15 minutes total today. Observe how your anxiety changes"),
                PlanDayStep(id: "x4", day: 4, reflection: "Sleep is a mercy from Allah. Anxiety thrives on exhaustion. Protect your sleep as an act of worship.", ayah: "And We made your sleep a means of rest.", ayahReference: "Quran 78:9", dhikr: "Recite Ayatul Kursi and the 3 Quls before sleeping", action: "Set a firm bedtime. No screens 30 minutes before. Read Quran instead"),
                PlanDayStep(id: "x5", day: 5, reflection: "Gratitude rewires the anxious brain. When you focus on what you have, fear of what you might lose diminishes.", ayah: "And He gave you from all you asked of Him. And if you should count the favor of Allah, you could not enumerate them.", ayahReference: "Quran 14:34", dhikr: "Say 'Alhamdulillah' 100 times, naming a specific blessing each time", action: "Write down 20 things — big and small — that are going right in your life"),
                PlanDayStep(id: "x6", day: 6, reflection: "Connection is the antidote to anxiety. Isolation amplifies worry. Be with people who calm your heart.", ayah: "And keep yourself patient with those who call upon their Lord in the morning and the evening.", ayahReference: "Quran 18:28", dhikr: "Make du'a for someone who also struggles with anxiety", action: "Spend quality time with someone you trust. Talk, laugh, or pray together"),
                PlanDayStep(id: "x7", day: 7, reflection: "A week of tawakkul and dhikr. Anxiety may not vanish overnight, but you now have tools rooted in faith. Trust the process, trust Allah, and be gentle with yourself.", ayah: "Allah does not burden a soul beyond that it can bear.", ayahReference: "Quran 2:286", dhikr: "Complete all morning and evening adhkar with full presence", action: "Write your personal anxiety action plan: what dhikr helps, what triggers to avoid, who to call, when to seek professional help"),
            ]
        ),
    ]
}
